# Get all worklogs for an accountId
GET https://api.tempo.io/core/3/worklogs/user/{{accountId}}
Authorization: Bearer {{token}}
###

# Post an individual worklog
POST https://api.tempo.io/core/3/worklogs
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "issueKey": "INT-10",
  "timeSpentSeconds": 3600,
  "startDate": "2022-06-16",
  "startTime": "08:00:00",
  "description": "Working on issue ISSUE",
  "authorAccountId": "{{accountId}}"
}
###

# Request approval
POST https://api.tempo.io/core/3/timesheet-approvals/user/{{accountId}}/submit?from=2022-06-01&to=2022-06-30
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "comment": "Please review my timesheet, Linh",
  "reviewerAccountId": "{{reviewerAccountId}}"
}
###
